blog_title = "Vinícius Müller's blog"
base_url = "https://viniciusmuler.github.io/blog"
author = "Vinícius Müller"

# extra_links_start = [
#     {name="About", href="/about.html"},
# ]

extra_links_end = [
    {name="GitHub", href="https://github.com/viniciusmuller"},
]
