[mdzk]
authors = ["Vinícius Müller"]
ignore = []
language = "en"
multilingual = false
src = "notes"
title = "My blog"
backlinks-header = "Backlinks"

[build]
create-missing = false
build-dir = "book"

[output.html]
no-section-label = true

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 1

#[preprocessor.toc]
#command = "mdbook-toc"
#renderer = ["html"]
