[mdzk]
authors = ["Vinícius Müller"]
ignore = []
language = "en"
multilingual = false
src = "notes"
title = "My blog"
backlinks-header = "Backlinks"

[build]
create-missing = false
build-dir = "book"
